### ISSUE TITLE
How to make a device to vibrate more than one time?

### ISSUE THREAD

**Issue by doowonee** [abhijitvalluri/fitnotifications#10]
It'd be wonderful for prevent missing from events.

**Comment by abhijitvalluri** [comment]
Hi, this is something that is beyond the scope of this app. That can only be done by modifying the firmware of the Fitbit device to behave differently when notifications arrive. This app simply relays notifications from your Android phone to the Fitbit device but does not modify the way the Fitbit device responds to the notifications. 

Only Fitbit can make this change in behavior. So it is best if you suggest this to them as a new feature.
