### ISSUE TITLE
Issues with latest Fitbit firmware (22.22.55.2)

### ISSUE THREAD

**Issue by TheAshladzz** [abhijitvalluri/fitnotifications#12]
Hello! :) Latest fitbit update (22.22.55.2) gave me some issues regarding Notifications. i am not recieving any notifications most of the time - and sometimes they come after a while.

Same happens when im using the Test button in the App.

Maybe fitbit crudded it for the Fit Notification app :octocat:

**Comment by abhijitvalluri** [comment]
Fitbit keeps messing up their notification setup. It is breath taking how terrible their notification support on Android is to this day. It is super flaky. Cannot do much but shrug and hope they fix it in the next release... Anyway this is a very old issue. Closing.
