### ISSUE TITLE
Feature Request: Prevent notifications if in silent / Do Not Disturb mode

### ISSUE THREAD

**Issue by Mayzie** [abhijitvalluri/fitnotifications#19]
The application ignores systemwide silent / do not disturb mode. I request that if it is in do not disturb, then do not forward notifications to the Fitbit device -- i.e. to stop being woken up at night, if you forget to go into the app and switch "Notification Service State" off.

Running Android 9 (OxygenOS 9.0.4). App version is the latest available from the Play Store, 2.9.17.

**Comment by abhijitvalluri** [comment]
There is already DND setting in the Settings page of the app dealing with the behavior of silent mode/DND mode. Please try that and see if that fixes your issue. You can either make the app to respect system DND setting or ignore. This feature was added a long time ago to give users options as some users requested this feature. 

I will close this issue as the feature exists.
