### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [abhijitvalluri/fitnotifications#23]
You can add Screenshots for F-Droid, too, if you want. https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/ https://gitlab.com/snippets/1895688 That was simply information about what is still possible. You would then only have to enter the screenshots in fastlane.

**Comment by abhijitvalluri** [comment]
Thanks for the info! I will look into it and add the screenshots to F-droid. It will be cool to have some nice flashy screenshots there as well 😄
