### ISSUE TITLE
Transliteration and typefaces

### ISSUE THREAD

**Issue by benjymous** [abhijitvalluri/fitnotifications#7]
I've noticed that there are a few regular ascii symbols that aren't included in the Fitbit Charge 2's in built typeface, so was going to add them to the transliteration data.

Before I make the change, my question was, do all the fitbit devices share the same typeface?

**Comment by abhijitvalluri** [comment]
May be, I am honestly not sure though. I can test if the characters you have added to the transliterations data are showing up on my Fitbit Blaze.

**Comment by benjymous** [comment]
I used the highly scientific method of creating notifications in Tasker containing lots of symbols, then noting which ones displayed as null squares on the fitbit

**Comment by abhijitvalluri** [comment]
Closing issue as PR #8 solves it.
